version: '3.5'

services:
  ya_service:
    container_name: yandex_service
    build:
      context: .
      dockerfile: ./docker/Dockerfile 
    ports:
      - "50051:50051"
      - "8081:8081"   
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres_container  
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    restart: unless-stopped

volumes:
  postgres:
